version: "3.8"
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "1k"
    max-file: "3"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - web
      - backend
    volumes:
      - ./docker/config/nginx-dev.conf:/etc/nginx/conf.d/default.conf

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    volumes:
      - ./web:/app
    logging: *default-logging

  backend:
    build:
      context: "./docker/php-fpm"
      dockerfile: "Dockerfile"
    links:
      - mysql
      - redis
    volumes:
      - ./:/var/www/html
    logging: *default-logging

  mysql:
    image: mysql
    volumes:
      - "./data/db:/var/lib/mysql"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "${DB_PASSWORD}"

  redis:
    image: redis:alpine
    command: "redis-server --requirepass ${REDIS_PASSWORD}"
    restart: always
    logging: *default-logging

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
